# Generated by Django 5.0.6 on 2024-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='coin_balance',
            field=models.IntegerField(default=0),
        ),
    ]
