# Generated by Django 5.0.6 on 2024-06-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('PAPER', 'Paper'), ('PLASTIC', 'Plastic'), ('GLASS', 'Glass'), ('METAL', 'Metal'), ('ELECTRONICS', 'Electronics'), ('ORGANIC', 'Organic'), ('TEXTILES', 'Textiles'), ('BATTERIES', 'Batteries'), ('WOOD', 'Wood'), ('RUBBER', 'Rubber'), ('MIXED_MATERIALS', 'Mixed Materials')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.member')),
            ],
        ),
    ]
