# Generated by Django 5.0.6 on 2024-08-05 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_queries_status_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
