# Generated by Django 5.0.7 on 2024-07-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='starting_bid',
        ),
    ]
