# Generated by Django 4.2.11 on 2024-07-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cartitem'),
        ('product', '0004_alter_product_image'),
    ]

    operations = [
    ]
