# Generated by Django 5.0.6 on 2024-08-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('question', 'Question'), ('feedback', 'Feedback'), ('suggestion', 'Suggestion')], max_length=20),
        ),
    ]
