# Generated by Django 4.2.11 on 2024-06-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unused_coins', models.IntegerField(default=0)),
                ('used_coins', models.IntegerField(default=0)),
                ('expired_coins', models.IntegerField(default=0)),
            ],
        ),
    ]
