# Generated by Django 5.0.7 on 2024-07-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unused_coins', models.IntegerField(default=0)),
                ('used_coins', models.IntegerField(default=0)),
                ('expired_coins', models.IntegerField(default=0)),
            ],
        ),
    ]
